#include "base_simulationConst.h"

void base_simulationConst::InitSimulationConst()
{
  atoms                        = 0;
  nQQatoms                     = 0;
  nLJatoms                     = 0;
  grid                         = GRID;
  gridBits                     = GRID_BITS;
  SMPCount                     = 0;
  ntp                          = 0;
  barostat                     = 1;
  alpb                         = 0;
  igb                          = 0;
  icnstph                      = 0;
  ti_mode                      = 0;
  icnste                       = 0;
  hybridgb                     = 0;
  ifmbar                       = 0;
  scnb                         = (1.0 / 2.0);
  scee                         = (1.0 / 1.2);
  cut                          = 8.0;
  cut2                         = cut * cut;
  cut3                         = cut2 * cut;
  cut6                         = cut3 * cut3;
  cutinv                       = 1.0 / cut;
  cut2inv                      = cutinv * cutinv;
  cut3inv                      = cut2inv * cutinv;
  cut6inv                      = cut3inv * cut3inv;
  fswitch                      = -1;
  fswitch2                     = 0.0;
  fswitch3                     = 0.0;
  fswitch6                     = 0.0;
  invfswitch6cut6              = 0.0;
  invfswitch3cut3              = 0.0;
  efx                          = 0;
  efy                          = 0;
  efz                          = 0;
  efn                          = 0;
  efphase                      = 0;
  effreq                       = 0;
  skinnb                       = 2.0f;
  cutPlusSkin                  = cut + skinnb;
  cutPlusSkin2                 = cutPlusSkin * cutPlusSkin;
  dielc                        = 1.0;
  tol                          = 0.0001;
  bUseVlimit                   = false;
  vlimit                       = -1.0;
  massH                        = 1.008;
  gb_alpha                     = 0.0;
  gb_beta                      = 0.0;
  gb_gamma                     = 0.0;
  gb_fs_max                    = 2.0;
  rgbmax                       = 25.0;
  intdiel                      = 1.0;
  extdiel                      = 78.5;
  alpb_alpha                   = 0.571412;
  saltcon                      = 0.0;
  surften                      = 0.005;
  offset                       = 0.09;
  gb_neckscale                 = 0.361825;
  gb_neckcut                   = 2.8;
  gb_neckoffset                = 1.0 - 0.09;
  gbion                        = 0;
  gi_coef_1                    = 1.0;
  gi_coef_2                    = 1.0;
  intdiel_ion_1                = 1.0;
  intdiel_ion_2                = 1.0;
  gb_neckscale_ion_1           = 1.0;
  gb_neckscale_ion_2           = 1.0;
  gi_coef_1_p                  = 1.0;
  gi_coef_1_n                  = 1.0;
  gi_coef_2_pp                 = 1.0;
  gi_coef_2_pn                 = 1.0;
  gi_coef_2_nn                 = 1.0;
  intdiel_ion_1_p              = 1.0;
  intdiel_ion_1_n              = 1.0;
  intdiel_ion_2_pp             = 1.0;
  intdiel_ion_2_pn             = 1.0;
  intdiel_ion_2_nn             = 1.0;
  gb_neckscale_ion_1_p         = 1.0;
  gb_neckscale_ion_1_n         = 1.0;
  gb_neckscale_ion_2_pp        = 1.0;
  gb_neckscale_ion_2_pn        = 1.0;
  gb_neckscale_ion_2_nn        = 1.0;
  arad                         = 15.0;
  a                            = 100.0;
  b                            = 100.0;
  c                            = 100.0;
  alpha                        = 90.0;
  beta                         = 90.0;
  gamma                        = 90.0;
  pi_vol_inv                   = 0.0;
  fac                          = 0.0;
  fac2                         = 0.0;
  is_orthog                    = true;
  paddedNumberOfAtoms          = 0;
  pAtomX                       = NULL;
  pAtomY                       = NULL;
  pAtomXYSP                    = NULL;
  pAtomZ                       = NULL;
  pAtomZSP                     = NULL;
  pAtomSigEps                  = NULL;
  pAtomLJID                    = NULL;
  pAtomRBorn                   = NULL;
  pAtomS                       = NULL;
  pgb_alpha                    = NULL;
  pgb_beta                     = NULL;
  pgb_gamma                    = NULL;
  pAtomInvMass                 = NULL;
  pAtomMass                    = NULL;
  pAtomCharge                  = NULL;
  pAtomChargeSP                = NULL;
  pAtomChargeSPLJID            = NULL;
  pReff                        = NULL;
  pReffSP                      = NULL;
  pPsi                         = NULL;
  pTemp7                       = NULL;
  pAtomIonMask                 = NULL;
  pBondedForceAccumulator      = NULL;
  pBondedForceXAccumulator     = NULL;
  pBondedForceYAccumulator     = NULL;
  pBondedForceZAccumulator     = NULL;
  pVelX                        = NULL;
  pVelY                        = NULL;
  pVelZ                        = NULL;
  pLVelX                       = NULL;
  pLVelY                       = NULL;
  pLVelZ                       = NULL;
  randomSteps                  = 0;
  randomNumbers                = 0;
  pRandom                      = NULL;
  pRandomX                     = NULL;
  pRandomY                     = NULL;
  pRandomZ                     = NULL;
  shakeConstraints             = 0;
  shakeOffset                  = 0;
  fastShakeConstraints         = 0;
  fastShakeOffset              = 0;
  slowShakeConstraints         = 0;
  slowShakeOffset              = 0;
  slowTIShakeConstraints       = 0;
  slowTIShakeOffset            = 0;
  tishake                      = 0;
  pShakeID                     = NULL;
  pShakeParm                   = NULL;
  pShakeInvMassH               = NULL;
  pFastShakeID                 = NULL;
  pSlowShakeID1                = NULL;
  pSlowShakeID2                = NULL;
  pSlowShakeParm               = NULL;
  pSlowShakeInvMassH           = NULL;
  pSlowTIShakeID1              = NULL;
  pSlowTIShakeID2              = NULL;
  pSlowTIShakeID3              = NULL;
  pSlowTIShakeParm             = NULL;
  pSlowTIShakeInvMassH         = NULL;
  pShakeParm2                  = NULL;
  pSlowShakeParm2              = NULL;
  pSlowTIShakeParm2            = NULL;
  pImageShakeID                = NULL;
  pImageFastShakeID            = NULL;
  pImageSlowShakeID1           = NULL;
  pImageSlowShakeID2           = NULL;
  pImageSlowTIShakeID1         = NULL;
  pImageSlowTIShakeID2         = NULL;
  pImageSlowTIShakeID3         = NULL;
  bonds                        = 0;
  bondAngles                   = 0;
  bondAngleOffset              = 0;
  dihedrals                    = 0;
  dihedralOffset               = 0;
  nb14s                        = 0;
  nb14Offset                   = 0;
  constraints                  = 0;
  constraintOffset             = 0;
  UBAngles                     = 0;
  UBAngleOffset                = 0;
  impDihedrals                 = 0;
  impDihedralOffset            = 0;
  cmaps                        = 0;
  cmapOffset                   = 0;
  pBond                        = NULL;
  pBondID                      = NULL;
  pBondAngle                   = NULL;
  pBondAngleID1                = NULL;
  pBondAngleID2                = NULL;
  pDihedral1                   = NULL;
  pDihedral2                   = NULL;
  pDihedral3                   = NULL;
  pDihedralID1                 = NULL;
  pNb141                       = NULL;
  pNb142                       = NULL;
  pNb14ID                      = NULL;
  pConstraint1                 = NULL;
  pConstraint2                 = NULL;
  pConstraintID                = NULL;
  pUBAngle                     = NULL;
  pUBAngleID                   = NULL;
  pImpDihedral                 = NULL;
  pImpDihedralID1              = NULL;
  pCmapID1                     = NULL;
  pCmapID2                     = NULL;
  pCmapType                    = NULL;
  pCmapEnergy                  = NULL;
  pLJTerm                      = NULL;
  pR4sources                   = NULL;
  LJTerms                      = 0;
  LJTypes                      = 0;
  ljexist[0]                   = 0xffffffff;
  ljexist[1]                   = 0xffffffff;
  ljexist[2]                   = 0xffffffff;
  ljexist[3]                   = 0xffffffff;
  nR4sources                   = 0;

  NMRR6av                      = false;
  NMRDistances                 = 0;
  NMRCOMDistances              = 0;
  NMRr6avDistances             = 0;
  NMRCOMAngles                 = 0;
  NMRCOMTorsions               = 0;
  NMRMaxgrp                    = 0;
  NMRDistanceOffset            = 0;
  NMRr6avDistanceOffset        = 0;
  NMRAngles                    = 0;
  NMRAngleOffset               = 0;
  NMRTorsions                  = 0;
  NMRTorsionOffset             = 0;
  bJar                         = false;
  drjar                        = 0.0;
  pNMRJarData                  = NULL;
  pNMRDistanceID               = NULL;
  pNMRDistanceR1R2             = NULL;
  pNMRDistanceR3R4             = NULL;
  pNMRDistanceK2K3             = NULL;
  pNMRDistanceAve              = NULL;
  pNMRDistanceTgtVal           = NULL;
  pNMRDistanceStep             = NULL;
  pNMRDistanceInc              = NULL;
  pNMRDistanceR1R2Slp          = NULL;
  pNMRDistanceR3R4Slp          = NULL;
  pNMRDistanceK2K3Slp          = NULL;
  pNMRDistanceR1R2Int          = NULL;
  pNMRDistanceR3R4Int          = NULL;
  pNMRDistanceK2K3Int          = NULL;
  pNMRTorsionTgtVal            = NULL;
  pNMRTorsionK4Slp             = NULL;

  pNMRCOMDistanceID            = NULL;
  pNMRCOMDistanceCOM           = NULL;
  pNMRCOMDistanceCOMGrp        = NULL;
  pNMRCOMDistanceR1R2          = NULL;
  pNMRCOMDistanceR3R4          = NULL;
  pNMRCOMDistanceK2K3          = NULL;
  pNMRCOMDistanceAve           = NULL;
  pNMRCOMDistanceTgtVal        = NULL;
  pNMRCOMDistanceStep          = NULL;
  pNMRCOMDistanceInc           = NULL;
  pNMRCOMDistanceR1R2Slp       = NULL;
  pNMRCOMDistanceR3R4Slp       = NULL;
  pNMRCOMDistanceK2K3Slp       = NULL;
  pNMRCOMDistanceR1R2Int       = NULL;
  pNMRCOMDistanceR3R4Int       = NULL;
  pNMRCOMDistanceK2K3Int       = NULL;
  pNMRCOMDistanceWeights       = NULL;
  pNMRCOMDistanceXYZ           = NULL;

  pNMRr6avDistanceID           = NULL;
  pNMRr6avDistancer6av         = NULL;
  pNMRr6avDistancer6avGrp      = NULL;
  pNMRr6avDistanceR1R2         = NULL;
  pNMRr6avDistanceR3R4         = NULL;
  pNMRr6avDistanceK2K3         = NULL;
  pNMRr6avDistanceAve          = NULL;
  pNMRr6avDistanceTgtVal       = NULL;
  pNMRr6avDistanceStep         = NULL;
  pNMRr6avDistanceInc          = NULL;
  pNMRr6avDistanceR1R2Slp      = NULL;
  pNMRr6avDistanceR3R4Slp      = NULL;
  pNMRr6avDistanceK2K3Slp      = NULL;
  pNMRr6avDistanceR1R2Int      = NULL;
  pNMRr6avDistanceR3R4Int      = NULL;
  pNMRr6avDistanceK2K3Int      = NULL;
  pNMRr6avDistanceWeights       = NULL;
  pNMRr6avDistanceXYZ           = NULL;

  pNMRAngleID1                 = NULL;
  pNMRAngleID2                 = NULL;
  pNMRAngleR1R2                = NULL;
  pNMRAngleR3R4                = NULL;
  pNMRAngleK2K3                = NULL;
  pNMRAngleAve                 = NULL;
  pNMRAngleTgtVal              = NULL;
  pNMRAngleStep                = NULL;
  pNMRAngleInc                 = NULL;
  pNMRAngleR1R2Slp             = NULL;
  pNMRAngleR3R4Slp             = NULL;
  pNMRAngleK2K3Slp             = NULL;
  pNMRAngleR1R2Int             = NULL;
  pNMRAngleR3R4Int             = NULL;
  pNMRAngleK2K3Int             = NULL;

  pNMRCOMAngleID1              = NULL;
  pNMRCOMAngleID2              = NULL;
  pNMRCOMAngleCOM           = NULL;
  pNMRCOMAngleCOMGrp        = NULL;
  pNMRCOMAngleR1R2          = NULL;
  pNMRCOMAngleR3R4          = NULL;
  pNMRCOMAngleK2K3          = NULL;
  pNMRCOMAngleAve           = NULL;
  pNMRCOMAngleTgtVal        = NULL;
  pNMRCOMAngleStep          = NULL;
  pNMRCOMAngleInc           = NULL;
  pNMRCOMAngleR1R2Slp       = NULL;
  pNMRCOMAngleR3R4Slp       = NULL;
  pNMRCOMAngleK2K3Slp       = NULL;
  pNMRCOMAngleR1R2Int       = NULL;
  pNMRCOMAngleR3R4Int       = NULL;
  pNMRCOMAngleK2K3Int       = NULL;

  pNMRTorsionID1               = NULL;
  pNMRTorsionR1R2              = NULL;
  pNMRTorsionR3R4              = NULL;
  pNMRTorsionK2K3              = NULL;
  pNMRTorsionAve1              = NULL;
  pNMRTorsionAve2              = NULL;
  pNMRAngleTgtVal              = NULL;
  pNMRTorsionStep              = NULL;
  pNMRTorsionInc               = NULL;
  pNMRTorsionR1R2Slp           = NULL;
  pNMRTorsionR3R4Slp           = NULL;
  pNMRTorsionK2K3Slp           = NULL;
  pNMRTorsionR1R2Int           = NULL;
  pNMRTorsionR3R4Int           = NULL;
  pNMRTorsionK2K3Int           = NULL;

  pNMRCOMTorsionID1            = NULL;
  pNMRCOMTorsionCOM            = NULL;
  pNMRCOMTorsionCOMGrp         = NULL;
  pNMRCOMTorsionR1R2           = NULL;
  pNMRCOMTorsionR3R4           = NULL;
  pNMRCOMTorsionK2K3           = NULL;
  pNMRCOMTorsionAve            = NULL;
  pNMRCOMTorsionTgtVal         = NULL;
  pNMRCOMTorsionStep           = NULL;
  pNMRCOMTorsionInc            = NULL;
  pNMRCOMTorsionR1R2Slp        = NULL;
  pNMRCOMTorsionR3R4Slp        = NULL;
  pNMRCOMTorsionK2K3Slp        = NULL;
  pNMRCOMTorsionR1R2Int        = NULL;
  pNMRCOMTorsionR3R4Int        = NULL;
  pNMRCOMTorsionK2K3Int        = NULL;

  EPs                          = 0;
  EP11s                        = 0;
  EP12s                        = 0;
  EP21s                        = 0;
  EP22s                        = 0;
  EPCustomCount                = 0;
  EP11Offset                   = 0;
  EP12Offset                   = 0;
  EP21Offset                   = 0;
  EP22Offset                   = 0;
  EPCustomOffset               = 0;
  pExtraPoint11Frame           = NULL;
  pExtraPoint11Index           = NULL;
  pExtraPoint11X               = NULL;
  pExtraPoint11Y               = NULL;
  pExtraPoint11Z               = NULL;
  pExtraPoint12Frame           = NULL;
  pExtraPoint12Index           = NULL;
  pExtraPoint12X               = NULL;
  pExtraPoint12Y               = NULL;
  pExtraPoint12Z               = NULL;
  pExtraPoint21Frame           = NULL;
  pExtraPoint21Index           = NULL;
  pExtraPoint21X1              = NULL;
  pExtraPoint21Y1              = NULL;
  pExtraPoint21Z1              = NULL;
  pExtraPoint21X2              = NULL;
  pExtraPoint21Y2              = NULL;
  pExtraPoint21Z2              = NULL;
  pExtraPoint22Frame           = NULL;
  pExtraPoint22Index           = NULL;
  pExtraPoint22X1              = NULL;
  pExtraPoint22Y1              = NULL;
  pExtraPoint22Z1              = NULL;
  pExtraPoint22X2              = NULL;
  pExtraPoint22Y2              = NULL;
  pExtraPoint22Z2              = NULL;
  pExtraPointCustomFrame       = NULL;
  pExtraPointCustomIndex       = NULL;
  pExtraPointCustomD1          = NULL;
  pExtraPointCustomD2          = NULL;
  pExtraPointCustomD3          = NULL;
  pImageExtraPoint11Frame      = NULL;
  pImageExtraPoint11Index      = NULL;
  pImageExtraPoint12Frame      = NULL;
  pImageExtraPoint12Index      = NULL;
  pImageExtraPoint21Frame      = NULL;
  pImageExtraPoint21Index      = NULL;
  pImageExtraPoint22Frame      = NULL;
  pImageExtraPoint22Index      = NULL;
  pImageEPCustomIndex          = NULL;
  pImageEPCustomFrame          = NULL;
  pChargeRefreshBuffer         = NULL;
  pForceAccumulator            = NULL;
  pForceXAccumulator           = NULL;
  pForceYAccumulator           = NULL;
  pForceZAccumulator           = NULL;
  pNBForceAccumulator          = NULL;
  pNBForceXAccumulator         = NULL;
  pNBForceYAccumulator         = NULL;
  pNBForceZAccumulator         = NULL;
  pIntForceAccumulator         = NULL;
  pIntForceXAccumulator        = NULL;
  pIntForceYAccumulator        = NULL;
  pIntForceZAccumulator        = NULL;
  pReffAccumulator             = NULL;
  pSumdeijdaAccumulator        = NULL;
  pEnergyBuffer                = NULL;
  pAFEBuffer                   = NULL;
  pGBBRPosition                = NULL;
  pGBNB1Position               = NULL;
  pGBNB2Position               = NULL;
  pNeckMaxValPos               = NULL;
  stride                       = 0;
  stride2                      = 0;
  stride3                      = 0;
  stride4                      = 0;
  imageStride                  = 0;
  ew_coeff                     = 1.0;
  ew_coeffSP                   = (PMEFloat)1.0;
  ew_coeff2                    = ew_coeffSP * ew_coeffSP;
  negTwoEw_coeffRsqrtPI        = (PMEFloat)(-2.0 * ew_coeff / sqrt(PI));
  nfft1                        = 0;
  nfft2                        = 0;
  nfft3                        = 0;
  dnfft1                       = 0.0;
  dnfft2                       = 0.0;
  dnfft3                       = 0.0;
  XYZStride                    = 0;
  fft_x_dim                    = 0;
  fft_y_dim                    = 0;
  fft_z_dim                    = 0;
  fft_y_dim_times_x_dim        = 0;
  pmeOrder                     = 4;
  orderMinusOne                = pmeOrder - 1;
  pPrefac1                     = NULL;
  pPrefac2                     = NULL;
  pPrefac3                     = NULL;
  pFractX                      = NULL;
  pFractY                      = NULL;
  pFractZ                      = NULL;
  plliXYZ_q                    = NULL;
  pXYZ_q                       = NULL;
  pXYZ_qt                      = NULL;
  pErfcCoeffsTable             = NULL;
  
  cells                        = 0;
  cell                         = (PMEFloat)1.0;
  xcell                        = (PMEDouble)1.0;
  ycell                        = (PMEDouble)1.0;
  zcell                        = (PMEDouble)1.0;
  minCellX                     = (PMEDouble)-2.0;
  minCellY                     = (PMEDouble)-2.0;
  minCellZ                     = (PMEDouble)-2.0;
  maxCellX                     = (PMEDouble)2.0;
  maxCellY                     = (PMEDouble)2.0;
  maxCellZ                     = (PMEDouble)2.0;
  oneOverXcells                = (PMEFloat)1.0;
  oneOverYcells                = (PMEFloat)1.0;
  oneOverZcells                = (PMEFloat)1.0;
  xcells                       = 0;
  ycells                       = 0;
  zcells                       = 0;
  NLExclusionBufferSize        = 0;
  pNTPData                     = NULL;
  pFinishedBlocksCounters      = NULL;
  pKernelCompletionFlags       = NULL;
  pNLbSkinTestFail             = NULL;
  pNLCellHash                  = NULL;
  pImageIndex                  = NULL;
  pImageIndex2                 = NULL;
  pImageAtom                   = NULL;
  pImageAtom2                  = NULL;
  pImageAtomLookup             = NULL;
  pImageHash                   = NULL;
  pAtomXYSaveSP                = NULL;
  pAtomZSaveSP                 = NULL;
  pImageX                      = NULL;
  pImageY                      = NULL;
  pImageZ                      = NULL;
  pImageVelX                   = NULL;
  pImageVelY                   = NULL;
  pImageVelZ                   = NULL;
  pImageLVelX                  = NULL;
  pImageLVelY                  = NULL;
  pImageLVelZ                  = NULL;
  pImageMass                   = NULL;
  pImageCharge                 = NULL;
  pImageSigEps                 = NULL;
  pImageLJID                   = NULL;
  pImageCellID                 = NULL;
  pImageX2                     = NULL;
  pImageY2                     = NULL;
  pImageZ2                     = NULL;
  pImageVelX2                  = NULL;
  pImageVelY2                  = NULL;
  pImageVelZ2                  = NULL;
  pImageLVelX2                 = NULL;
  pImageLVelY2                 = NULL;
  pImageLVelZ2                 = NULL;
  pImageMass2                  = NULL;
  pImageCharge2                = NULL;
  pImageSigEps2                = NULL;
  pImageLJID2                  = NULL;
  pImageCellID2                = NULL;
  pImageNMRCOMDistanceID       = NULL;
  pImageNMRCOMDistanceCOM      = NULL;
  pImageNMRCOMDistanceCOMGrp   = NULL;
  pImageNMRr6avDistanceID      = NULL;
  pImageNMRr6avDistancer6av    = NULL;
  pImageNMRr6avDistancer6avGrp = NULL;
  pImageNMRCOMAngleID1         = NULL;
  pImageNMRCOMAngleID2         = NULL;
  pImageNMRCOMAngleCOM         = NULL;
  pImageNMRCOMAngleCOMGrp      = NULL;
  pImageNMRCOMTorsionID1       = NULL;
  pImageNMRCOMTorsionCOM       = NULL;
  pImageNMRCOMTorsionCOMGrp    = NULL;
  pImageSoluteAtomID           = NULL;
  pImageSolventAtomID          = NULL;
  pExclusion                   = NULL;
  pWorkUnit                    = NULL;
  pOldAtomX                    = NULL;
  pOldAtomY                    = NULL;
  pOldAtomZ                    = NULL;
  pShakeOldAtomX               = NULL;
  pShakeOldAtomY               = NULL;
  pShakeOldAtomZ               = NULL;
  pTIRegion                    = NULL;
  pTILinearAtmID               = NULL;
  pBarLambda                   = NULL;
  pXMax                        = NULL;
  pYMax                        = NULL;
  pZMax                        = NULL;
  pXMin                        = NULL;
  pYMin                        = NULL;
  pZMin                        = NULL;
  pImageHash2                  = NULL;
  pImageInvMass                = NULL;
  pImageTIRegion               = NULL;
  pImageTILinearAtmID          = NULL;
  pUpdateIndex                 = NULL;
  pImageInvMass2               = NULL;
  pImageTIRegion2              = NULL;
  pImageTILinearAtmID2         = NULL;
  pBNLExclusionBuffer          = NULL;
  pNLNonbondCellStartEnd       = NULL;
  pNLExclusionStartCount       = NULL;
  pNLExclusionList             = NULL;
  pNLAtomList                  = NULL;
  pNLTotalOffset               = NULL;
  pNLRecord                    = NULL;
  pNLEntry                     = NULL;
  pNLEntries                   = NULL;
  pNLOffset                    = NULL;
  pFrcBlkCounters              = NULL;
  maxNonbonds                  = 0;
  forceBufferStride            = 0;
  soluteMolecules              = 0;
  soluteAtoms                  = 0;
  solventMolecules             = 0;
  solventMoleculeStride        = 0;
  pSoluteAtomMoleculeID        = NULL;
  pSoluteAtomID                = NULL;
  pSoluteAtomMass              = NULL;
  pSoluteCOMX                  = NULL;
  pSoluteCOMY                  = NULL;
  pSoluteCOMZ                  = NULL;
  pSoluteDeltaCOMX             = NULL;
  pSoluteDeltaCOMY             = NULL;
  pSoluteDeltaCOMZ             = NULL;
  pSoluteUllCOMX               = NULL;
  pSoluteUllCOMY               = NULL;
  pSoluteUllCOMZ               = NULL;
  pSoluteUllEKCOMX             = NULL;
  pSoluteUllEKCOMY             = NULL;
  pSoluteUllEKCOMZ             = NULL;
  pSoluteInvMass               = NULL;
  pSolventAtomID               = NULL;
  pSolventAtomMass1            = NULL;
  pSolventAtomMass2            = NULL;
  pSolventAtomMass3            = NULL;
  pSolventAtomMass4            = NULL;
  pSolventCOMX                 = NULL;
  pSolventCOMY                 = NULL;
  pSolventCOMZ                 = NULL;
  pSolventInvMass              = NULL;
  pKineticEnergy               = NULL;
  pAFEKineticEnergy            = NULL;
  pConstraintAtomX             = NULL;
  pConstraintAtomY             = NULL;
  pConstraintAtomZ             = NULL;
  pConstraintCOMX              = NULL;
  pConstraintCOMY              = NULL;
  pConstraintCOMZ              = NULL;

  // Bonded term work units
  pBwuInstructions             = NULL;
  pBwuBondID                   = NULL;
  pBwuAnglID                   = NULL;
  pBwuDiheID                   = NULL;
  pBwuCmapID                   = NULL;
  pBwuQQxcID                   = NULL;
  pBwuNB14ID                   = NULL;
  pBwuNMR2ID                   = NULL;
  pBwuNMR3ID                   = NULL;
  pBwuNMR4ID                   = NULL;
  pBwuUreyID                   = NULL;
  pBwuCImpID                   = NULL;
  pQQxcID                      = NULL;
  pBwuBond                     = NULL;
  pBwuAngl                     = NULL;
  pBwuNMR2                     = NULL;
  pBwuNMR3                     = NULL;
  pBwuNMR4                     = NULL;
  pBwuUrey                     = NULL;
  pBwuCImp                     = NULL;
  pBwuCharges                  = NULL;
  pBwuDihe12                   = NULL;
  pBwuDihe3                    = NULL;

  // Atom shuttling
  nShuttle                     = 0;
  pDataShuttle                 = NULL;
  pShuttleTickets              = NULL;

  //NEB parameters
  neb_nbead               = 0;
  beadid                  = 0;
  nattgtrms               = 0;
  nattgtfit               = 0;
  last_neb_atm            = 0;
  skmin                   = 50;
  skmax                   = 100;
  tmode                   = 1;
  pRMSMask                = NULL;
  pFitMask                = NULL;
  pAtmIdx                 = NULL;
  pNEBEnergyAll           = NULL;
  pTangents               = NULL;
  pSpringForce            = NULL;
  pNEBForce               = NULL;
  pNextDataShuttle        = NULL;
  pPrevDataShuttle        = NULL;
  pKabschCOM              = NULL;
  pDataSPR                = NULL;
  pRotAtm                 = NULL;
  ptotFitMass             = NULL;

  // MCWat Parameters
  stericBitCellWidth      = 4;
  stericBitCellHeight     = 4;
  stericBitCellDepth      = 2;
  waterAtomCount          = 3;
  coarseMaxXvxl           = 0;
  coarseMaxYvxl           = 0;
  coarseMaxZvxl           = 0;
  coarseMaxAtoms          = 0;
  coarseGridSpacing       = 0.0;
  mcressize               = 0;
  stericMaxXVxl           = 0;
  stericMaxYVxl           = 0;
  stericMaxZVxl           = 0;
  stericGridSpacing       = 0.0;
  pStericRadius           = NULL;
  pVoxelOffset            = NULL;
  pStericEmptyVoxels      = NULL;
  pStericGrid             = NULL;
  pStericThreadCount      = NULL;
  pCoarseGrid             = NULL;
  pRandomWater            = NULL;
  pCoarseTrans            = NULL;
  pCoarseGridEne          = NULL;

  // General IPS parameters
  bIPSActive                   = false;
  rips                         = (PMEFloat)8.0;
  eipssnb                      = 0.0;
  eipssel                      = 0.0;
  virips                       = 0.0;

  // Electrostatic IPS parameters:
  aipse0                       = -35.0 / 16.0;
  aipse1                       = 35.0 / 16.0;
  aipse2                       = -21.0 / 16.0;
  aipse3                       = 5.0 / 16.0;
  pipsec                       = 1.0 + aipse0 + aipse1 + aipse2 + aipse3;
  pipse0                       = aipse0 - pipsec;
  bipse1                       = 2.0 * aipse1;
  bipse2                       = 4.0 * aipse2;
  bipse3                       = 6.0 * aipse3;

  // Dispersion IPS parameters:
  aipsvc0                      = 7.0 / 16.0;
  aipsvc1                      = 9.0 / 14.0;
  aipsvc2                      = -3.0 / 28.0;
  aipsvc3                      = 6.0 / 7.0;
  pipsvcc                      = 1.0 + aipsvc0 + aipsvc1 + aipsvc2 + aipsvc3;
  pipsvc0                      = aipsvc0 - pipsvcc;
  bipsvc1                      = 2.0 * aipsvc1;
  bipsvc2                      = 4.0 * aipsvc2;
  bipsvc3                      = 6.0 * aipsvc3;

  // Repulsion IPS parameters:
  aipsva0                      = 5.0 / 787.0;
  aipsva1                      = 9.0 / 26.0;
  aipsva2                      = -3.0 / 13.0;
  aipsva3                      = 27.0 / 26.0;
  pipsvac                      = 1.0 + aipsva0 + aipsva1 + aipsva2 + aipsva3;
  pipsva0                      = aipsva0 - pipsvac;
  bipsva1                      = 4.0 * aipsva1;
  bipsva2                      = 8.0 * aipsva2;
  bipsva3                      = 12.0 * aipsva3;

  // Derived parameters
  rips2                        = rips * rips;
  ripsr                        = (PMEFloat)1.0 / (rips);
  rips2r                       = (PMEFloat)1.0 / rips2;
  rips6r                       = rips2r * rips2r * rips2r;
  rips12r                      = rips6r * rips6r;
  rgbmax1i                     = 1.0 / rgbmax;
  rgbmax2i                     = rgbmax1i * rgbmax1i;
  rgbmaxpsmax2                 = (rgbmax + gb_fs_max) * (rgbmax + gb_fs_max);
  alpb_beta                    = alpb_alpha * (intdiel / extdiel);
  one_arad_beta                = alpb_beta / arad;
  if (saltcon >= 0) {
    gb_kappa                   = 0.73 * sqrt(0.10806 * saltcon);
    if (gb_kappa > 0.0) {
      gb_kappa_inv             = 1.0 / gb_kappa;
    }
  }
  else {
    gb_kappa                   = 0.0;
    gb_kappa_inv               = 0.0;
  }
  if (alpb == 0) {
    intdiel_inv                = 1.0 / intdiel;
    extdiel_inv                = 1.0 / extdiel;
  }
  else {
    extdiel_inv                = 1.0 / (extdiel * (1.0 + alpb_beta));
    intdiel_inv                = 1.0 / (intdiel * (1.0 + alpb_beta));
  }
  invMassH                     = 1.0 / massH;

  // Periodic boundary conditions
  ucellf[0][0]                 = a;
  ucellf[0][1]                 = 0.0;
  ucellf[0][2]                 = 0.0;
  ucellf[1][0]                 = 0.0;
  ucellf[1][1]                 = b;
  ucellf[1][2]                 = 0.0;
  ucellf[2][0]                 = 0.0;
  ucellf[2][1]                 = 0.0;
  ucellf[2][2]                 = c;
  ucell[0][0]                  = ucellf[0][0];
  ucell[0][1]                  = ucellf[0][1];
  ucell[0][2]                  = ucellf[0][2];
  ucell[1][0]                  = ucellf[1][0];
  ucell[1][1]                  = ucellf[1][1];
  ucell[1][2]                  = ucellf[1][2];
  ucell[2][0]                  = ucellf[2][0];
  ucell[2][1]                  = ucellf[2][1];
  ucell[2][2]                  = ucellf[2][2];
  recipf[0][0]                 = 1.0 / a;
  recipf[0][1]                 = 0.0;
  recipf[0][2]                 = 0.0;
  recipf[1][0]                 = 0.0;
  recipf[1][1]                 = 1.0 / b;
  recipf[1][2]                 = 0.0;
  recipf[2][0]                 = 0.0;
  recipf[2][1]                 = 0.0;
  recipf[2][2]                 = 1.0 / c;
  recip[0][0]                  = recipf[0][0];
  recip[0][1]                  = recipf[0][1];
  recip[0][2]                  = recipf[0][2];
  recip[1][0]                  = recipf[1][0];
  recip[1][1]                  = recipf[1][1];
  recip[1][2]                  = recipf[1][2];
  recip[2][0]                  = recipf[2][0];
  recip[2][1]                  = recipf[2][1];
  recip[2][2]                  = recipf[2][2];
  pbc_box[0]                   = a;
  pbc_box[1]                   = b;
  pbc_box[2]                   = c;
  reclng[0]                    = 1.0 / a;
  reclng[1]                    = 1.0 / b;
  reclng[2]                    = 1.0 / c;
  uc_volume                    = a * b * c;
  uc_sphere                    = sqrt(a*a + b*b + c*c);
  NLMaxTotalOffset             = 0;

  // Set up AMD parameters
  iamd                         = 0;
  iamdlag                      = 1;
  amd_print_interval           = 0;
  amd_EthreshP                 = 0.0;
  amd_alphaP                   = 0.0;
  amd_EthreshD                 = 0.0;
  amd_alphaD                   = 0.0;
  amd_EthreshP_w               = 0.0;
  amd_alphaP_w                 = 0.0;
  amd_EthreshD_w               = 0.0;
  amd_alphaD_w                 = 0.0;
  amd_w_sign                   = 1.0;
  amd_temp0                    = 0.0;
  AMDNumLag                    = 0;
  AMDNumRecs                   = -1;
  AMDtboost                    = 0.0;
  pAMDfwgtd                    = NULL;
  AMDfwgt                      = 1.0;
  pAMDEDihedral                = NULL;

  // Set up GaMD parameters
  igamd                        = 0;
  igamd0                       = 0;
  igamdlag                     = 1;
  gamd_print_interval          = 0;
  tspan                        = 0;
  tspanP                       = 0;
  tspanD                       = 0;
  gamd_EthreshP                = 0.0;
  gamd_kP                      = 0.0;
  gamd_EthreshD                = 0.0;
  gamd_kD                      = 0.0;
  gamd_EthreshB                = 0.0;
  gamd_kB                      = 0.0;
  gamd_temp0                   = 0.0;
  GaMDNumLag                   = 0;
  GaMDNumRecs                  = -1;
  GaMDtboost                   = 0.0;
  pGaMDfwgtd                   = NULL;
  GaMDfwgt                     = 1.0;
  GaMDfwgtb                    = 1.0;
  pGaMDEDihedral               = NULL;

  // Set up scaledMD parameters
  scaledMD                     = 0;
  scaledMD_lambda              = 1.0;
  scaledMD_energy              = 0.0;
  scaledMD_weight              = 0.0;
  scaledMD_unscaled_energy     = 0.0;

  // Set up SGLD parameters
  isgld                        = 0;
  nsgatom                      = 0;
  sgavg                   = 0.0;
  sgavp                   = 0.0;
  sgft                   = 0.0;
  sgff                   = 0.0;
  sgfg                   = 0.0;
  fsgldg                   = 0.0;
  tempsg                   = 300.0;
  tsgset                   = 300.0;
  sgmsum                   = 0.0;
  sgrndf                   = 0.0;
    // SGLD pointers
  pWsg                   = NULL;                              // SGLD weighter
  pX0sg                   = NULL;                              // local average X 
  pY0sg                   = NULL;                              // local average Y 
  pZ0sg                   = NULL;                              // local average Z 
  pX1sg                   = NULL;                              // local average X 
  pY1sg                   = NULL;                              // local average Y 
  pZ1sg                   = NULL;                              // local average Z 
  pX2sg                   = NULL;                              // local average X1 
  pY2sg                   = NULL;                              // local average Y1 
  pZ2sg                   = NULL;                              // local average Z1 
  pRsgX                   = NULL;                              // local average X random forces
  pRsgY                   = NULL;                              // local average Y random forces
  pRsgZ                   = NULL;                              // local average Z random forces
  pFPsg                   = NULL;                              // local average of momentums time forces
  pPPsg                   = NULL;                              // local average of momentums time momentums
  pImageWsg                   = NULL;                              // SGLD weighter
  pImageX0sg                   = NULL;                         // Image x local average 
  pImageY0sg                   = NULL;                         // Image y local average 
  pImageZ0sg                   = NULL;                         // Image z local average 
  pImageX1sg                   = NULL;                         // Image x local average 
  pImageY1sg                   = NULL;                         // Image y local average 
  pImageZ1sg                   = NULL;                         // Image z local average 
  pImageX2sg                   = NULL;                         // Image x1 local average 
  pImageY2sg                   = NULL;                         // Image y1 local average 
  pImageZ2sg                   = NULL;                         // Image z1 local average 
  pImageRsgX                   = NULL;                         // Image local average X random forces
  pImageRsgY                   = NULL;                         // Image local average Y random forces
  pImageRsgZ                   = NULL;                         // Image local average Z random forces
  pImageFPsg                   = NULL;                         // Image local average of forces time momentum
  pImagePPsg                   = NULL;                         // Image local average of momentum time momentum
  pImageWsg2                   = NULL;                              // SGLD weighter
  pImageX0sg2                   = NULL;                         // Image x 
  pImageY0sg2                   = NULL;                         // Image y 
  pImageZ0sg2                   = NULL;                         // Image z 
  pImageX1sg2                   = NULL;                         // Image x local average 
  pImageY1sg2                   = NULL;                         // Image y local average 
  pImageZ1sg2                   = NULL;                         // Image z local average 
  pImageX2sg2                   = NULL;                         // Image x1 local average 
  pImageY2sg2                   = NULL;                         // Image y1 local average 
  pImageZ2sg2                   = NULL;                         // Image z1 local average 
  pImageRsgX2                   = NULL;                         // Image local average X random forces
  pImageRsgY2                   = NULL;                         // Image local average Y random forces
  pImageRsgZ2                   = NULL;                         // Image local average Z random forces
  pImageFPsg2                   = NULL;                         // Image local average of forces time momentum
  pImagePPsg2                   = NULL;                         // Image local average of momentum time momentum
 // SGLD calculation pointer
  pSGLDAverage                   = NULL;   


  // Set up alchemical free energy parameters
  AFElambda[0]                 = 0.0;
  AFElambda[1]                 = 1.0;
  AFElambdaSP[0]               = 0.0;
  AFElambdaSP[1]               = 1.0;
  scalpha                      = 0.5;
  scalphaSP                    = 0.5;
  scbeta                       = 12.0;
  scbetaSP                     = 12.0;
  bar_intervall                = 100;
  bar_states                   = 0;
  bar_stride                   = 0;
  TIsigns[0]                   = -1.0;
  TIsigns[1]                   = 1.0;
  TIPaddedLinearAtmCnt         = 0;
  TIlinearAtmCnt               = 0;
  AFE_recip_region             = 1;
  pBarTot                      = NULL;
  pAFEMolType                  = NULL;
  pAFEMolPartner               = NULL;
  pEELT                        = NULL;
  pEELTE                       = NULL;
  pEVDW                        = NULL;
  pEVDWE                       = NULL;
  pEGB                         = NULL;
  pEBond                       = NULL;
  pEAngle                      = NULL;
  pEDihedral                   = NULL;
  pEEL14                       = NULL;
  pENB14                       = NULL;
  pEConstraint                 = NULL;
  pEER                         = NULL;
  pEED                         = NULL;
  pEEDE                        = NULL;
  pEAngle_UB                   = NULL;
  pEImp                        = NULL;
  pECmap                       = NULL;
  pENMRDistance                = NULL;
  pENMRCOMDistance             = NULL;
  pENMRr6avDistance            = NULL;
  pENMRAngle                   = NULL;
  pENMRCOMAngle                = NULL;
  pENMRTorsion                 = NULL;
  pENMRCOMTorsion              = NULL;
  pEEField                     = NULL;
  pDVDL                        = NULL;
  pSCBondR1                    = NULL;
  pSCBondR2                    = NULL;
  pSCBondAngleR1               = NULL;
  pSCBondAngleR2               = NULL;
  pSCDihedralR1                = NULL;
  pSCDihedralR2                = NULL;
  pESCNMRDistanceR1            = NULL;
  pESCNMRDistanceR2            = NULL;
  pESCNMRCOMDistanceR1         = NULL;
  pESCNMRCOMDistanceR2         = NULL;
  pESCNMRr6avDistanceR1        = NULL;
  pESCNMRr6avDistanceR2        = NULL;
  pESCNMRAngleR1               = NULL;
  pESCNMRAngleR2               = NULL;
  pESCNMRTorsionR1             = NULL;
  pESCNMRTorsionR2             = NULL;
  pSCVDWDirR1                  = NULL;
  pSCVDWDirR2                  = NULL;
  pSCEELDirR1                  = NULL;
  pSCEELDirR2                  = NULL;
  pSCVDW14R1                   = NULL;
  pSCVDW14R2                   = NULL;
  pSCEEL14R1                   = NULL;
  pSCEEL14R2                   = NULL;
  pSCVDWDerR1                  = NULL;
  pSCVDWDerR2                  = NULL;
  pSCEELDerR1                  = NULL;
  pSCEELDerR2                  = NULL;
  pVirial                      = NULL;
  pVirial_11                   = NULL;
  pVirial_22                   = NULL;
  pVirial_33                   = NULL;
  pEKCOMX                      = NULL;
  pEKCOMY                      = NULL;
  pEKCOMZ                      = NULL;
  //continuous pHMD stuff
  qsetlam                      = false;
  use_forces                   = true;
  ntitr                        = 0;
  iphmd                        = 0;
  phmd_padded_ntitr            = 0;
  phmd_stride                  = 1;
  phmd_atom_stride             = 1;
  qmass_phmd                   = 10.0;
  temp_phmd                    = 300.0;
  phbeta                       = 5.0;
  randomNumbersPHMD            = 0;
  ptitratoms                   = NULL;
  pRandomPHMD                  = NULL;
  pdph_theta                   = NULL;
  pdph_accumulator             = NULL;
  pdph_plus_accumulator        = NULL;
  pphmd_ene                    = NULL;
  pvph_theta                   = NULL;
  pdudls                       = NULL;
  pvphold                      = NULL;
  pph_theta                    = NULL;
  pdphold                      = NULL;
  presbounds                   = NULL;
  pbaseres                     = NULL;
  psp_grp                      = NULL;
  pqstate1                     = NULL;
  pqstate2                     = NULL;
  pqstate1_md                  = NULL;
  pqstate2_md                  = NULL;
  pvstate1                     = NULL;
  pvstate2                     = NULL;
  pImageVstate1                = NULL;
  pImageVstate2                = NULL;
  pImageVstate12               = NULL;
  pImageVstate22               = NULL;
  pcharge_phmd                 = NULL;
  pparmod                      = NULL;
  pbarr                        = NULL;
  ppark                        = NULL;
  ppara                        = NULL;
  pparb                        = NULL;
  psp_par                      = NULL;
  padded_numch                 = 0;
  pexcludeatoms                = NULL;
  pgrplist                     = NULL;
  plinkgrplist                 = NULL;
  pImageGrplist                = NULL;
  pImageGrplist2               = NULL;
  pImageIndexPHMD              = NULL;
  pImageIndexPHMD2             = NULL;

  texImageX                    = 0;
  texImageX2                   = 0;
  texAtomX                     = 0;
  texXYZ_q                     = 0;
  texOldAtomX                  = 0;
#if !defined(use_DPFP)
  texAtomXYSP                  = 0;
  texAtomChargeSPLJID          = 0;
  texLJTerm                    = 0;
  texAtomZSP                   = 0;
  texErfcCoeffsTable           = 0;
#endif
}
